// This module is included in the following assemblies:
//
// assembly-upgrading-kafka-versions.adoc

[id='proc-upgrading-brokers-newer-kafka-{context}']

= Upgrading brokers to a newer Kafka version

This procedure will describe how to upgrade a {ProductName} Kafka cluster from one version to another.

.Prerequisites

* The Cluster Operator up and running.
* A `Kafka` resource to be upgraded to a Kafka version supported by the running Cluster Operator.
* You have checked that your `Kafka.spec.kafka.config` contains no options which are not supported in the version of Kafka being upgraded to.

.Procedure

. Update the `Kafka` resource. In `Kafka.spec.kafka.version` specify the version being upgraded _to_.
If the image to be used is different from the image for the given version of Kafka configured in the Cluster Operator's
`STRIMZI_KAFKA_IMAGE_MAP` then configure the `Kafka.spec.kafka.image`.
In `Kafka.spec.kafka.config` set `log.message.format.version` to the version being upgraded _from_. 
For example:
+
[source,yaml]
----
apiVersion: v1alpha1
kind: Kafka
spec:
  # ...
  kafka:
    version: 2.0.0
    config:
      log.message.format.version=1.1.1
      # ...
----

. Wait for the Cluster Operator to upgrade the cluster
**TODO** How will the user know when it is finished?

. Upgrade each client application to use the new version of the client libraries.
+
NOTE: If, for whatever reason, you need to revert the update at this point, follow the procedure xref:proc-downgradings-brokers-older-kafka-{context}[]. You will not be able to downgrade after this step.

. Update the `Kafka` resource to remove `log.message.format.version` from the `Kafka.spec.kafka.config`.
+
[source,yaml]
----
apiVersion: v1alpha1
kind: Kafka
spec:
  # ...
  kafka:
    version: 2.0.0
    config:
      # ...
----

. Wait for the Cluster Operator to update the cluster

.Additional resources